// ============================================================
// Menuzin — Payment Types (Multi-tenant Mercado Pago)
// Aligned with Supabase table schemas
// ============================================================

// ----- Enums -----

export type PaymentStatus =
  | "pending"
  | "processing"
  | "approved"
  | "rejected"
  | "cancelled"
  | "refunded"
  | "expired"
  | "charged_back";

export type OrderStatus =
  | "draft"
  | "pending_payment"
  | "new"
  | "confirmed"
  | "preparing"
  | "out_for_delivery"
  | "ready_for_pickup"
  | "completed"
  | "cancelled";

export type PaymentProvider = "mercadopago" | "manual";

export type PaymentMethod =
  | "pix_online"
  | "credit_card"
  | "debit_card"
  | "pix_manual"
  | "cash"
  | "card_on_delivery";

// ----- Supabase Table Types -----

/** stores */
export interface Store {
  id: string;
  name: string;
  slug: string;
  whatsapp?: string;
  status: "active" | "suspended" | "trial";
  created_at: string;
  updated_at: string;
}

/** store_payment_settings */
export interface StorePaymentSettings {
  id: string;
  store_id: string;
  provider: PaymentProvider;
  // Mercado Pago OAuth
  mp_user_id?: string;
  mp_public_key?: string;
  mp_access_token_encrypted?: string; // AES-GCM encrypted — NEVER expose on frontend
  mp_refresh_token_encrypted?: string; // AES-GCM encrypted — NEVER expose on frontend
  mp_token_expires_at?: string; // ISO timestamp
  mp_connected: boolean;
  mp_live_mode: boolean;
  // Manual payment methods
  pix_manual_key?: string;
  pix_manual_key_type?: "cpf" | "cnpj" | "email" | "phone" | "random";
  pix_manual_receiver?: string;
  cash_enabled: boolean;
  pix_manual_enabled: boolean;
  card_on_delivery_enabled: boolean;
  // Online payment methods (requires mp_connected)
  pix_enabled: boolean;
  credit_card_enabled: boolean;
  debit_card_enabled: boolean;
  created_at: string;
  updated_at: string;
}

/** Safe version of StorePaymentSettings for frontend (no tokens) */
export type StorePaymentSettingsSafe = Omit<
  StorePaymentSettings,
  "mp_access_token_encrypted" | "mp_refresh_token_encrypted"
> & {
  mp_public_key?: string; // Exposed only if needed for SDK init
};

/** orders */
export interface Order {
  id: string;
  store_id: string;
  order_number: number;
  customer_name: string;
  customer_whatsapp: string;
  customer_email?: string;
  order_type: "entrega" | "retirada" | "consumo_local";
  status: OrderStatus;
  payment_status: PaymentStatus;
  payment_method?: PaymentMethod;
  subtotal: number;
  delivery_fee: number;
  total: number;
  // Mercado Pago references
  mp_payment_id?: string;
  mp_order_id?: string;
  mp_status?: string;
  mp_status_detail?: string;
  created_at: string;
  updated_at: string;
}

/** payments */
export interface Payment {
  id: string;
  store_id: string;
  order_id: string;
  provider: PaymentProvider;
  provider_payment_id?: string;
  provider_order_id?: string;
  amount: number;
  payment_method: PaymentMethod;
  status: PaymentStatus;
  status_detail?: string;
  raw_response?: Record<string, unknown>; // jsonb — full MP response
  created_at: string;
  updated_at: string;
}

/** webhook_events */
export interface WebhookEvent {
  id: string;
  provider: PaymentProvider;
  event_type: string;
  provider_event_id?: string;
  store_id?: string;
  order_id?: string;
  payload: Record<string, unknown>; // jsonb — raw webhook body
  processed: boolean;
  created_at: string;
}

// ----- Edge Function Request / Response Types -----

/** mp-connect-start */
export interface MpConnectStartRequest {
  store_id: string;
}
export interface MpConnectStartResponse {
  authorization_url: string;
}

/** mp-oauth-callback (query params) */
export interface MpOAuthCallbackParams {
  code: string;
  state: string;
}

/** create-transparent-payment — Pix */
export interface CreatePixPaymentRequest {
  store_slug: string;
  order_id: string;
  payment_method: "pix_online";
  payer: {
    email: string;
    first_name: string;
    last_name: string;
    identification?: { type: "CPF" | "CNPJ"; number: string };
  };
}

/** create-transparent-payment — Card */
export interface CreateCardPaymentRequest {
  store_slug: string;
  order_id: string;
  payment_method: "credit_card" | "debit_card";
  card_token: string; // Generated by MP SDK on frontend
  installments: number;
  payer: {
    email: string;
    first_name: string;
    last_name: string;
    identification: { type: "CPF" | "CNPJ"; number: string };
  };
}

export type CreatePaymentRequest =
  | CreatePixPaymentRequest
  | CreateCardPaymentRequest;

/** Pix payment data returned to frontend */
export interface PixPaymentData {
  qr_code: string; // Pix copia-e-cola string
  qr_code_base64: string; // Base64 image for QR rendering
  ticket_url?: string;
  expires_at?: string; // ISO timestamp
  payment_id: string;
  payment_status: PaymentStatus;
}

/** Card payment data returned to frontend */
export interface CardPaymentData {
  payment_id: string;
  payment_status: PaymentStatus;
  status_detail?: string;
  order_id: string;
}

export type CreatePaymentResponse =
  | { type: "pix"; data: PixPaymentData }
  | { type: "card"; data: CardPaymentData };

// ----- UI State Types -----

export type MpConnectionStatus =
  | "connected"
  | "disconnected"
  | "expired"
  | "error"
  | "connecting"
  | "loading";

export interface PaymentFlowState {
  method: PaymentMethod | null;
  pixData: PixPaymentData | null;
  cardData: CardPaymentData | null;
  paymentStatus: PaymentStatus | null;
  isLoading: boolean;
  error: string | null;
}
