// Planos estáticos exibidos na landing page. Conteúdo institucional —
// não pertence ao banco (a fonte de verdade em runtime é public.plans).
export const plans = [
  {
    id: "presenca",
    name: "Presença",
    price: 0,
    highlight: false,
    tagline: "Comece grátis com sua vitrine no Guia Menuzin.",
    cta: "Cadastrar grátis",
    features: [
      "Página no Guia Menuzin",
      "Até 20 produtos e 4 categorias",
      "Cardápio digital com QR Code",
      "Botão de WhatsApp",
      "Estatísticas básicas",
      "Marca Menuzin visível",
    ],
  },
  {
    id: "start",
    name: "Start",
    price: 57.9,
    highlight: true,
    tagline: "Pedidos organizados no painel, prontos para vender.",
    cta: "Começar a vender",
    features: [
      "Tudo do Presença",
      "Produtos e categorias ilimitados",
      "Painel de pedidos (entrega e retirada)",
      "Status do pedido em tempo real",
      "Cadastro de clientes",
      "Taxa fixa por bairro",
      "Cupons básicos e impressão manual",
      "Relatórios básicos • até 2 usuários",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: 127.9,
    highlight: false,
    tagline: "Automação completa e pagamento online.",
    cta: "Profissionalizar meu delivery",
    features: [
      "Tudo do Start",
      "Pagamento online (Mercado Pago)",
      "Impressão automática (cozinha + entrega)",
      "Adicionais avançados, combos e pizza multi-sabor",
      "Cupons avançados, upsell e recuperação",
      "Taxa de entrega por distância",
      "Relatórios completos e múltiplos usuários",
      "Destaque no Guia Menuzin • suporte prioritário",
    ],
  },
] as const;
