// Planos estáticos exibidos na landing page. Conteúdo institucional —
// não pertence ao banco (a fonte da verdade em runtime é public.plans).
export const plans = [
  {
    id: "presenca",
    name: "Presença",
    price: 0,
    highlight: false,
    tagline: "Comece grátis com sua vitrine no Guia Menuzin.",
    cta: "Cadastrar grátis",
    features: [
      "Página no Guia Menuzin",
      "Até 20 produtos e 4 categorias",
      "Cardápio digital com QR Code",
      "Botão de WhatsApp",
      "Estatísticas básicas",
      "Marca Menuzin visível",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: 79.9,
    highlight: true,
    tagline: "Automação completa, pagamento online e destaque no Guia.",
    cta: "Profissionalizar meu delivery",
    features: [
      "Tudo do Presença",
      "Produtos e categorias ilimitados",
      "Painel de pedidos (entrega e retirada)",
      "Status do pedido em tempo real",
      "Cadastro de clientes",
      "Adicionais simples e taxa fixa por bairro",
      "Cupons básicos e impressão manual",
      "Pagamento online (Mercado Pago)",
      "Impressão automática (cozinha + entrega)",
      "Adicionais avançados, combos e pizza multi-sabor",
      "Cupons avançados, upsell e recuperação",
      "Taxa de entrega por distância",
      "Relatórios completos",
      "Múltiplos usuários",
      "Destaque no Guia Menuzin",
      "Suporte prioritário",
      "Sem marca Menuzin",
    ],
  },
] as const;
