/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PlatformLojasRouteImport } from './routes/platform.lojas'
import { Route as PlatformDashboardRouteImport } from './routes/platform.dashboard'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as AdminTrocarSenhaRouteImport } from './routes/admin.trocar-senha'
import { Route as AdminTaxasEntregaRouteImport } from './routes/admin.taxas-entrega'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminAparenciaRouteImport } from './routes/admin.aparencia'
import { Route as AdminAdicionaisRouteImport } from './routes/admin.adicionais'
import { Route as SlugPedidoConfirmadoRouteImport } from './routes/$slug.pedido-confirmado'
import { Route as AdminConfiguracoesIndexRouteImport } from './routes/admin.configuracoes.index'
import { Route as PlatformTenantsNovoRouteImport } from './routes/platform.tenants.novo'
import { Route as LojaSlugPedidoConfirmadoRouteImport } from './routes/loja.$slug.pedido-confirmado'
import { Route as ApiPublicQzCertDotcrtRouteImport } from './routes/api.public.qz-cert[.]crt'
import { Route as ApiPublicQzRouteImport } from './routes/api.public.qz'
import { Route as AdminConfiguracoesPedidosRouteImport } from './routes/admin.configuracoes.pedidos'
import { Route as AdminConfiguracoesPagamentosRouteImport } from './routes/admin.configuracoes.pagamentos'
import { Route as AdminConfiguracoesImpressoraRouteImport } from './routes/admin.configuracoes.impressora'
import { Route as SlugAcompanharOrderIdRouteImport } from './routes/$slug.acompanhar.$orderId'
import { Route as LojaSlugAcompanharOrderIdRouteImport } from './routes/loja.$slug.acompanhar.$orderId'

const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformLojasRoute = PlatformLojasRouteImport.update({
  id: '/platform/lojas',
  path: '/platform/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformDashboardRoute = PlatformDashboardRouteImport.update({
  id: '/platform/dashboard',
  path: '/platform/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrocarSenhaRoute = AdminTrocarSenhaRouteImport.update({
  id: '/admin/trocar-senha',
  path: '/admin/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTaxasEntregaRoute = AdminTaxasEntregaRouteImport.update({
  id: '/admin/taxas-entrega',
  path: '/admin/taxas-entrega',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/admin/cupons',
  path: '/admin/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAparenciaRoute = AdminAparenciaRouteImport.update({
  id: '/admin/aparencia',
  path: '/admin/aparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdicionaisRoute = AdminAdicionaisRouteImport.update({
  id: '/admin/adicionais',
  path: '/admin/adicionais',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugPedidoConfirmadoRoute = SlugPedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => SlugRoute,
} as any)
const AdminConfiguracoesIndexRoute = AdminConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminConfiguracoesRoute,
} as any)
const PlatformTenantsNovoRoute = PlatformTenantsNovoRouteImport.update({
  id: '/platform/tenants/novo',
  path: '/platform/tenants/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugPedidoConfirmadoRoute =
  LojaSlugPedidoConfirmadoRouteImport.update({
    id: '/pedido-confirmado',
    path: '/pedido-confirmado',
    getParentRoute: () => LojaSlugRoute,
  } as any)
const ApiPublicQzCertDotcrtRoute = ApiPublicQzCertDotcrtRouteImport.update({
  id: '/api/public/qz-cert.crt',
  path: '/api/public/qz-cert.crt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQzRoute = ApiPublicQzRouteImport.update({
  id: '/api/public/qz',
  path: '/api/public/qz',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesPedidosRoute =
  AdminConfiguracoesPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesPagamentosRoute =
  AdminConfiguracoesPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesImpressoraRoute =
  AdminConfiguracoesImpressoraRouteImport.update({
    id: '/impressora',
    path: '/impressora',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const SlugAcompanharOrderIdRoute = SlugAcompanharOrderIdRouteImport.update({
  id: '/acompanhar/$orderId',
  path: '/acompanhar/$orderId',
  getParentRoute: () => SlugRoute,
} as any)
const LojaSlugAcompanharOrderIdRoute =
  LojaSlugAcompanharOrderIdRouteImport.update({
    id: '/acompanhar/$orderId',
    path: '/acompanhar/$orderId',
    getParentRoute: () => LojaSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/$slug/pedido-confirmado': typeof SlugPedidoConfirmadoRoute
  '/admin/adicionais': typeof AdminAdicionaisRoute
  '/admin/aparencia': typeof AdminAparenciaRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRouteWithChildren
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/taxas-entrega': typeof AdminTaxasEntregaRoute
  '/admin/trocar-senha': typeof AdminTrocarSenhaRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/lojas': typeof PlatformLojasRoute
  '/admin/': typeof AdminIndexRoute
  '/$slug/acompanhar/$orderId': typeof SlugAcompanharOrderIdRoute
  '/admin/configuracoes/impressora': typeof AdminConfiguracoesImpressoraRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/pedidos': typeof AdminConfiguracoesPedidosRoute
  '/api/public/qz': typeof ApiPublicQzRoute
  '/api/public/qz-cert.crt': typeof ApiPublicQzCertDotcrtRoute
  '/loja/$slug/pedido-confirmado': typeof LojaSlugPedidoConfirmadoRoute
  '/platform/tenants/novo': typeof PlatformTenantsNovoRoute
  '/admin/configuracoes/': typeof AdminConfiguracoesIndexRoute
  '/loja/$slug/acompanhar/$orderId': typeof LojaSlugAcompanharOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/$slug/pedido-confirmado': typeof SlugPedidoConfirmadoRoute
  '/admin/adicionais': typeof AdminAdicionaisRoute
  '/admin/aparencia': typeof AdminAparenciaRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/taxas-entrega': typeof AdminTaxasEntregaRoute
  '/admin/trocar-senha': typeof AdminTrocarSenhaRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/lojas': typeof PlatformLojasRoute
  '/admin': typeof AdminIndexRoute
  '/$slug/acompanhar/$orderId': typeof SlugAcompanharOrderIdRoute
  '/admin/configuracoes/impressora': typeof AdminConfiguracoesImpressoraRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/pedidos': typeof AdminConfiguracoesPedidosRoute
  '/api/public/qz': typeof ApiPublicQzRoute
  '/api/public/qz-cert.crt': typeof ApiPublicQzCertDotcrtRoute
  '/loja/$slug/pedido-confirmado': typeof LojaSlugPedidoConfirmadoRoute
  '/platform/tenants/novo': typeof PlatformTenantsNovoRoute
  '/admin/configuracoes': typeof AdminConfiguracoesIndexRoute
  '/loja/$slug/acompanhar/$orderId': typeof LojaSlugAcompanharOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/$slug/pedido-confirmado': typeof SlugPedidoConfirmadoRoute
  '/admin/adicionais': typeof AdminAdicionaisRoute
  '/admin/aparencia': typeof AdminAparenciaRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRouteWithChildren
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/taxas-entrega': typeof AdminTaxasEntregaRoute
  '/admin/trocar-senha': typeof AdminTrocarSenhaRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/lojas': typeof PlatformLojasRoute
  '/admin/': typeof AdminIndexRoute
  '/$slug/acompanhar/$orderId': typeof SlugAcompanharOrderIdRoute
  '/admin/configuracoes/impressora': typeof AdminConfiguracoesImpressoraRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/pedidos': typeof AdminConfiguracoesPedidosRoute
  '/api/public/qz': typeof ApiPublicQzRoute
  '/api/public/qz-cert.crt': typeof ApiPublicQzCertDotcrtRoute
  '/loja/$slug/pedido-confirmado': typeof LojaSlugPedidoConfirmadoRoute
  '/platform/tenants/novo': typeof PlatformTenantsNovoRoute
  '/admin/configuracoes/': typeof AdminConfiguracoesIndexRoute
  '/loja/$slug/acompanhar/$orderId': typeof LojaSlugAcompanharOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/$slug/pedido-confirmado'
    | '/admin/adicionais'
    | '/admin/aparencia'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/taxas-entrega'
    | '/admin/trocar-senha'
    | '/loja/$slug'
    | '/platform/dashboard'
    | '/platform/lojas'
    | '/admin/'
    | '/$slug/acompanhar/$orderId'
    | '/admin/configuracoes/impressora'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/pedidos'
    | '/api/public/qz'
    | '/api/public/qz-cert.crt'
    | '/loja/$slug/pedido-confirmado'
    | '/platform/tenants/novo'
    | '/admin/configuracoes/'
    | '/loja/$slug/acompanhar/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/$slug/pedido-confirmado'
    | '/admin/adicionais'
    | '/admin/aparencia'
    | '/admin/categorias'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/taxas-entrega'
    | '/admin/trocar-senha'
    | '/loja/$slug'
    | '/platform/dashboard'
    | '/platform/lojas'
    | '/admin'
    | '/$slug/acompanhar/$orderId'
    | '/admin/configuracoes/impressora'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/pedidos'
    | '/api/public/qz'
    | '/api/public/qz-cert.crt'
    | '/loja/$slug/pedido-confirmado'
    | '/platform/tenants/novo'
    | '/admin/configuracoes'
    | '/loja/$slug/acompanhar/$orderId'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/$slug/pedido-confirmado'
    | '/admin/adicionais'
    | '/admin/aparencia'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/taxas-entrega'
    | '/admin/trocar-senha'
    | '/loja/$slug'
    | '/platform/dashboard'
    | '/platform/lojas'
    | '/admin/'
    | '/$slug/acompanhar/$orderId'
    | '/admin/configuracoes/impressora'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/pedidos'
    | '/api/public/qz'
    | '/api/public/qz-cert.crt'
    | '/loja/$slug/pedido-confirmado'
    | '/platform/tenants/novo'
    | '/admin/configuracoes/'
    | '/loja/$slug/acompanhar/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AdminAdicionaisRoute: typeof AdminAdicionaisRoute
  AdminAparenciaRoute: typeof AdminAparenciaRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRouteWithChildren
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminTaxasEntregaRoute: typeof AdminTaxasEntregaRoute
  AdminTrocarSenhaRoute: typeof AdminTrocarSenhaRoute
  LojaSlugRoute: typeof LojaSlugRouteWithChildren
  PlatformDashboardRoute: typeof PlatformDashboardRoute
  PlatformLojasRoute: typeof PlatformLojasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicQzRoute: typeof ApiPublicQzRoute
  ApiPublicQzCertDotcrtRoute: typeof ApiPublicQzCertDotcrtRoute
  PlatformTenantsNovoRoute: typeof PlatformTenantsNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/lojas': {
      id: '/platform/lojas'
      path: '/platform/lojas'
      fullPath: '/platform/lojas'
      preLoaderRoute: typeof PlatformLojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/dashboard': {
      id: '/platform/dashboard'
      path: '/platform/dashboard'
      fullPath: '/platform/dashboard'
      preLoaderRoute: typeof PlatformDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trocar-senha': {
      id: '/admin/trocar-senha'
      path: '/admin/trocar-senha'
      fullPath: '/admin/trocar-senha'
      preLoaderRoute: typeof AdminTrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/taxas-entrega': {
      id: '/admin/taxas-entrega'
      path: '/admin/taxas-entrega'
      fullPath: '/admin/taxas-entrega'
      preLoaderRoute: typeof AdminTaxasEntregaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/aparencia': {
      id: '/admin/aparencia'
      path: '/admin/aparencia'
      fullPath: '/admin/aparencia'
      preLoaderRoute: typeof AdminAparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/adicionais': {
      id: '/admin/adicionais'
      path: '/admin/adicionais'
      fullPath: '/admin/adicionais'
      preLoaderRoute: typeof AdminAdicionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/pedido-confirmado': {
      id: '/$slug/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/$slug/pedido-confirmado'
      preLoaderRoute: typeof SlugPedidoConfirmadoRouteImport
      parentRoute: typeof SlugRoute
    }
    '/admin/configuracoes/': {
      id: '/admin/configuracoes/'
      path: '/'
      fullPath: '/admin/configuracoes/'
      preLoaderRoute: typeof AdminConfiguracoesIndexRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/platform/tenants/novo': {
      id: '/platform/tenants/novo'
      path: '/platform/tenants/novo'
      fullPath: '/platform/tenants/novo'
      preLoaderRoute: typeof PlatformTenantsNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug/pedido-confirmado': {
      id: '/loja/$slug/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/loja/$slug/pedido-confirmado'
      preLoaderRoute: typeof LojaSlugPedidoConfirmadoRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/api/public/qz-cert.crt': {
      id: '/api/public/qz-cert.crt'
      path: '/api/public/qz-cert.crt'
      fullPath: '/api/public/qz-cert.crt'
      preLoaderRoute: typeof ApiPublicQzCertDotcrtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/qz': {
      id: '/api/public/qz'
      path: '/api/public/qz'
      fullPath: '/api/public/qz'
      preLoaderRoute: typeof ApiPublicQzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes/pedidos': {
      id: '/admin/configuracoes/pedidos'
      path: '/pedidos'
      fullPath: '/admin/configuracoes/pedidos'
      preLoaderRoute: typeof AdminConfiguracoesPedidosRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/pagamentos': {
      id: '/admin/configuracoes/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/configuracoes/pagamentos'
      preLoaderRoute: typeof AdminConfiguracoesPagamentosRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/impressora': {
      id: '/admin/configuracoes/impressora'
      path: '/impressora'
      fullPath: '/admin/configuracoes/impressora'
      preLoaderRoute: typeof AdminConfiguracoesImpressoraRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/$slug/acompanhar/$orderId': {
      id: '/$slug/acompanhar/$orderId'
      path: '/acompanhar/$orderId'
      fullPath: '/$slug/acompanhar/$orderId'
      preLoaderRoute: typeof SlugAcompanharOrderIdRouteImport
      parentRoute: typeof SlugRoute
    }
    '/loja/$slug/acompanhar/$orderId': {
      id: '/loja/$slug/acompanhar/$orderId'
      path: '/acompanhar/$orderId'
      fullPath: '/loja/$slug/acompanhar/$orderId'
      preLoaderRoute: typeof LojaSlugAcompanharOrderIdRouteImport
      parentRoute: typeof LojaSlugRoute
    }
  }
}

interface SlugRouteChildren {
  SlugPedidoConfirmadoRoute: typeof SlugPedidoConfirmadoRoute
  SlugAcompanharOrderIdRoute: typeof SlugAcompanharOrderIdRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugPedidoConfirmadoRoute: SlugPedidoConfirmadoRoute,
  SlugAcompanharOrderIdRoute: SlugAcompanharOrderIdRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AdminConfiguracoesRouteChildren {
  AdminConfiguracoesImpressoraRoute: typeof AdminConfiguracoesImpressoraRoute
  AdminConfiguracoesPagamentosRoute: typeof AdminConfiguracoesPagamentosRoute
  AdminConfiguracoesPedidosRoute: typeof AdminConfiguracoesPedidosRoute
  AdminConfiguracoesIndexRoute: typeof AdminConfiguracoesIndexRoute
}

const AdminConfiguracoesRouteChildren: AdminConfiguracoesRouteChildren = {
  AdminConfiguracoesImpressoraRoute: AdminConfiguracoesImpressoraRoute,
  AdminConfiguracoesPagamentosRoute: AdminConfiguracoesPagamentosRoute,
  AdminConfiguracoesPedidosRoute: AdminConfiguracoesPedidosRoute,
  AdminConfiguracoesIndexRoute: AdminConfiguracoesIndexRoute,
}

const AdminConfiguracoesRouteWithChildren =
  AdminConfiguracoesRoute._addFileChildren(AdminConfiguracoesRouteChildren)

interface LojaSlugRouteChildren {
  LojaSlugPedidoConfirmadoRoute: typeof LojaSlugPedidoConfirmadoRoute
  LojaSlugAcompanharOrderIdRoute: typeof LojaSlugAcompanharOrderIdRoute
}

const LojaSlugRouteChildren: LojaSlugRouteChildren = {
  LojaSlugPedidoConfirmadoRoute: LojaSlugPedidoConfirmadoRoute,
  LojaSlugAcompanharOrderIdRoute: LojaSlugAcompanharOrderIdRoute,
}

const LojaSlugRouteWithChildren = LojaSlugRoute._addFileChildren(
  LojaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AdminAdicionaisRoute: AdminAdicionaisRoute,
  AdminAparenciaRoute: AdminAparenciaRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRouteWithChildren,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminTaxasEntregaRoute: AdminTaxasEntregaRoute,
  AdminTrocarSenhaRoute: AdminTrocarSenhaRoute,
  LojaSlugRoute: LojaSlugRouteWithChildren,
  PlatformDashboardRoute: PlatformDashboardRoute,
  PlatformLojasRoute: PlatformLojasRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicQzRoute: ApiPublicQzRoute,
  ApiPublicQzCertDotcrtRoute: ApiPublicQzCertDotcrtRoute,
  PlatformTenantsNovoRoute: PlatformTenantsNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
