/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as LojaSlugPedidoConfirmadoRouteImport } from './routes/loja.$slug.pedido-confirmado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugPedidoConfirmadoRoute =
  LojaSlugPedidoConfirmadoRouteImport.update({
    id: '/pedido-confirmado',
    path: '/pedido-confirmado',
    getParentRoute: () => LojaSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/loja/$slug/pedido-confirmado': typeof LojaSlugPedidoConfirmadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/loja/$slug/pedido-confirmado': typeof LojaSlugPedidoConfirmadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/loja/$slug/pedido-confirmado': typeof LojaSlugPedidoConfirmadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loja/$slug' | '/loja/$slug/pedido-confirmado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loja/$slug' | '/loja/$slug/pedido-confirmado'
  id: '__root__' | '/' | '/loja/$slug' | '/loja/$slug/pedido-confirmado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LojaSlugRoute: typeof LojaSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug/pedido-confirmado': {
      id: '/loja/$slug/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/loja/$slug/pedido-confirmado'
      preLoaderRoute: typeof LojaSlugPedidoConfirmadoRouteImport
      parentRoute: typeof LojaSlugRoute
    }
  }
}

interface LojaSlugRouteChildren {
  LojaSlugPedidoConfirmadoRoute: typeof LojaSlugPedidoConfirmadoRoute
}

const LojaSlugRouteChildren: LojaSlugRouteChildren = {
  LojaSlugPedidoConfirmadoRoute: LojaSlugPedidoConfirmadoRoute,
}

const LojaSlugRouteWithChildren = LojaSlugRoute._addFileChildren(
  LojaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LojaSlugRoute: LojaSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
